openapi: 3.0.0
info:
  title: Prices Scraper API
  description: API for managing product scraping, notifications, and reports
  version: 1.0.0

servers:
  - url: http://localhost:{port}/api
    description: Local development server
    variables:
      port:
        default: "8081"
        description: The port number for the API server

paths:

  /products:
    $ref: './paths/products.yaml#/products'
  /products/scraped:
    $ref: './paths/products.yaml#/products_scraped'
  /products/{id}:
    $ref: './paths/products.yaml#/products_id'

  /categories:
    $ref: './paths/categories.yaml#/categories'
  /categories/{id}:
    $ref: './paths/categories.yaml#/categories_id'

  /scraper:
    $ref: './paths/scraper.yaml#/scraper'
  /scraper/test:
    $ref: './paths/scraper.yaml#/scraper_test'
  /scraper/enables:
    $ref: './paths/scraper.yaml#/scraper_enables'
  /scraper/{id}:
    $ref: './paths/scraper.yaml#/scraper_id'

  /notifications:
    $ref: './paths/notifications.yaml#/notifications'
  /notifications/{id}:
    $ref: './paths/notifications.yaml#/notifications_id'

  /reports/product-scraped:
    $ref: './paths/reports.yaml#/reports_product_scraped' 

  /product-category:
    $ref: './paths/productCategory.yaml#/product_category'
  /product-category/product/{productId}:
    $ref: './paths/productCategory.yaml#/product_category_by_product'
  /product-category/category/{categoryId}:
    $ref: './paths/productCategory.yaml#/product_category_by_category'
  /product-category/assign:
    $ref: './paths/productCategory.yaml#/product_category_assign'
  /product-category/{productId}/{categoryId}:
    $ref: './paths/productCategory.yaml#/product_category_delete'