openapi: 3.0.0
info:
  title: Prices Scraper API
  description: API for managing product scraping, notifications, and reports
  version: 1.0.0

servers:
  - url: http://{host}:{port}/api
    description: Local development server
    variables:
      host:
        default: "localhost"
        description: The host where the API server is running
      port:
        default: "8081"
        description: The port number for the API server

paths:

  /products:
    $ref: './paths/products.yaml#/products'
  /products/scraped:
    $ref: './paths/products.yaml#/products_scraped'
  /products/scraped-product/{productId}:
    $ref: './paths/products.yaml#/products_scraped_product'
  /products/{id}:
    $ref: './paths/products.yaml#/products_id'

  /categories:
    $ref: './paths/categories.yaml#/categories'
  /categories/{id}:
    $ref: './paths/categories.yaml#/categories_id'

  /lists:
    $ref: './paths/lists.yaml#/lists'
  /lists/{id}:
    $ref: './paths/lists.yaml#/lists_id'
  /lists/create:
    $ref: './paths/lists.yaml#/lists_create'

  /product-list:
    $ref: './paths/productList.yaml#/product_list'
  /product-list/product/{productId}:
    $ref: './paths/productList.yaml#/product_list_by_product'
  /product-list/list/{listId}:
    $ref: './paths/productList.yaml#/product_list_by_list'
  /product-list/assign:
    $ref: './paths/productList.yaml#/product_list_assign'
  /product-list/{productId}/{listId}:
    $ref: './paths/productList.yaml#/product_list_delete'
  /product-list/scraped-product/{listId}:
    $ref: './paths/productList.yaml#/product_list_scraped_by_list'

  /scraper:
    $ref: './paths/scraper.yaml#/scraper'
  /scraper/test:
    $ref: './paths/scraper.yaml#/scraper_test'
  /scraper/enables:
    $ref: './paths/scraper.yaml#/scraper_enables'
  /scraper/{id}:
    $ref: './paths/scraper.yaml#/scraper_id'
  /scraper/suggest-selectors:
    $ref: './paths/scraper.yaml#/suggest-selectors'
  /scraper/product-details-by-selectors:
    $ref: './paths/scraper.yaml#/product-details-by-selectors'

  /notifications:
    get:
      $ref: './paths/notifications.yaml#/notifications/get'
    post:
      $ref: './paths/notifications.yaml#/notifications/post'
  /notifications/{id}:
    get:
      $ref: './paths/notifications.yaml#/notifications_id/get'
    put:
      $ref: './paths/notifications.yaml#/notifications_id/put'
  /notifications/product-scraped/{id}:
    get:
      $ref: './paths/notifications.yaml#/notifications_product_scraped/get'

  /reports/product-scraped:
    $ref: './paths/reports.yaml#/reports_product_scraped' 

  /product-category:
    $ref: './paths/productCategory.yaml#/product_category'
  /product-category/product/{productId}:
    $ref: './paths/productCategory.yaml#/product_category_by_product'
  /product-category/category/{categoryId}:
    $ref: './paths/productCategory.yaml#/product_category_by_category'
  /product-category/assign:
    $ref: './paths/productCategory.yaml#/product_category_assign'
  /product-category/{productId}/{categoryId}:
    $ref: './paths/productCategory.yaml#/product_category_delete'
  /product-category/scraped-product/{categoryId}:
    $ref: './paths/productCategory.yaml#/product_category_scraped_by_category'