ProductListAssignment:
  type: object
  properties:
    product_id:
      type: integer
      description: The product ID
    list_id:
      type: integer
      description: The list ID
    product_name:
      type: string
      description: The name of the product
    list_name:
      type: string
      description: The name of the list
    created_at:
      type: string
      format: date-time
      description: The creation timestamp
    updated_at:
      type: string
      format: date-time
      description: The last update timestamp
  required:
    - product_id
    - list_id
    - product_name
    - list_name
    - created_at
    - updated_at 